#include "keymap_common.h"
#include "backlight.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* Layer 0: QWERTY */
    KEYMAP(\
        ESC, F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12, PSCR,PAUS, \
        GRV, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   MINS,EQL, BSPC,PGUP, \
        TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,BSLS,PGDN, \
        FN0, A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,SLCK,ENT, DEL,  \
        LSFT,     Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,RSFT,UP,  FN1,  \
        LCTL,LGUI,LALT,               SPC,           RALT,NO,  RCTL,LEFT,DOWN,RGHT),
    /* Layer 1: Space fn */
    KEYMAP(\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        FN2, TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        FN3, TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,               FN4,           TRNS,NO,  TRNS,TRNS,TRNS,TRNS),
    /* Layer 2: Mouse */
    KEYMAP(\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,BTN3,BTN1,BTN2, \
        TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,WH_D,MS_U,WH_U, \
        TRNS,TRNS,TRNS,               TRNS,          TRNS,NO,  TRNS,MS_L,MS_D,MS_R),
    /* Layer 3: Toggle */
    KEYMAP(\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        FN5, FN6, FN7, FN8, FN9, FN10,FN11,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,               TRNS,          TRNS,NO,  TRNS,TRNS,TRNS,TRNS),
    /* Layer 4: Functions */
    KEYMAP(\
        SLEP,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,PWR, TRNS, \
        TRNS,MSEL,VOLU,MPLY,PSCR,SLCK,PAUS,HOME,INS, DEL, END, TRNS,TRNS,TRNS,TRNS, \
        CAPS,MPRV,VOLD,MNXT,TRNS,TRNS,LEFT,DOWN,UP,  RGHT,TRNS,TRNS,TRNS,WSCH,TRNS, \
        TRNS,     MUTE,TRNS,TRNS,TRNS,TRNS,FN12,PGDN,PGUP,TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,               TRNS,          TRNS,NO,  TRNS,TRNS,TRNS,TRNS)
};

const uint16_t PROGMEM fn_actions[] = {
    [0]  = ACTION_LAYER_TAP_KEY(3, KC_CAPS),
    [1]  = ACTION_LAYER_MOMENTARY(4),
    [2]  = ACTION_MODS_KEY(MOD_RSFT, KC_GRV),
    [3]  = ACTION_LAYER_TAP_KEY(3, KC_ESC),
    [4]  = ACTION_LAYER_TAP_KEY(4, KC_SPACE),
    [5]  = ACTION_LAYER_SET_CLEAR(0),
    [6]  = ACTION_LAYER_TOGGLE(1),
    [7]  = ACTION_LAYER_TOGGLE(2),
    [8]  = ACTION_BACKLIGHT_LEVEL(BACKLIGHT_SWITCH),
    [9]  = ACTION_BACKLIGHT_LEVEL(BACKLIGHT_RGBRED),
    [10] = ACTION_BACKLIGHT_LEVEL(BACKLIGHT_RGBGREEN),
    [11] = ACTION_BACKLIGHT_LEVEL(BACKLIGHT_RGBBLUE),
    [12] = ACTION_MODS_KEY(MOD_LSFT, KC_INS),
};
